Genre.create!([
  {name: "Tango"},
  {name: "Vals"},
  {name: "Milonga"},
  {name: "Candombe"},
  {name: "Foxtrot"},
  {name: "Otros Ritmos"}
])
Song.create!([
  {title: "A La Luz Del Candil", composer: "Carlos Vicente Geroni Flores", lyricist: "Julio Navarrine", year: 1927, genre_id: 1},
  {title: "A Media Luz", composer: "Edgardo Donato", lyricist: "Carlos Lenzi", year: 1924, genre_id: 1},
  {title: "A Mi Madre (Con Los Amigos)", composer: "Carlos Gardel", lyricist: "Andres Cepeda", year: nil, genre_id: 2},
  {title: "Abandono", composer: "Pedro Maffia", lyricist: "Homero Manzi", year: nil, genre_id: 1},
  {title: "Acquaforte", composer: "Horacio Pettorossi", lyricist: "Juan Carlos Marambio Catan", year: 1932, genre_id: 1},
  {title: "Adios Arrabal", composer: "Juan Bauer", lyricist: "Carlos Lenzi", year: 1930, genre_id: 1},
  {title: "Adios Buenos Aires", composer: "Eduardo Arolas", lyricist: "Leopoldo Torres Rios", year: nil, genre_id: 1},
  {title: "Adios Pampa Mia", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1945, genre_id: 1},
  {title: "Afiches", composer: "Atilio Stampone", lyricist: "Homero Exposito", year: nil, genre_id: 1},
  {title: "Ahora No Me Conoces", composer: "Armando Baliotti", lyricist: "Carlos Giampetruzzi (Giampe)", year: 1941, genre_id: 1},
  {title: "Al Compas De Un Tango", composer: "Alberto Suarez Villanueva", lyricist: "Oscar Rubens", year: 1942, genre_id: 1},
  {title: "Al Compas Del Corazon (Late Un Corazon)", composer: "Domingo Federico", lyricist: "Homero Exposito", year: 1942, genre_id: 1},
  {title: "Al Verla Pasar", composer: "Joaquin Mora", lyricist: "Jose Maria Contursi", year: nil, genre_id: 1},
  {title: "Alas Rotas", composer: "Edgardo Donato", lyricist: "Maruja Pacheco Huergo", year: nil, genre_id: 1},
  {title: "Alma De Bohemio", composer: "Roberto Firpo", lyricist: "Juan Andres Caruso", year: 1914, genre_id: 1},
  {title: "Alma Mia", composer: "Diego Centeno", lyricist: "Hector Marco", year: 1936, genre_id: 2},
  {title: "Amarras", composer: "Carlos Marchisio", lyricist: "Carmelo Santiago", year: 1944, genre_id: 1},
  {title: "Amigos Que Yo Quiero", composer: "Hugo Gutierrez", lyricist: "Hugo Gutierrez", year: nil, genre_id: 1},
  {title: "Amurado", composer: "Pedro Maffia", lyricist: "Jose De Grandis", year: 1927, genre_id: 1},
  {title: "Anclao En Paris", composer: "Guillermo Barbieri", lyricist: "Enrique Cadicamo", year: 1931, genre_id: 1},
  {title: "Anoche A Las Dos", composer: "Raul De Los Hoyos", lyricist: "Roberto Lino Cayol", year: 1926, genre_id: 1},
  {title: "Asi Se Baila El Tango", composer: "Elias Randal", lyricist: "Marvil (Elizardo Martinez Vilas)", year: 1942, genre_id: 1},
  {title: "Atenti Pebeta", composer: "Ciriaco Ortiz", lyricist: "Celedonio Flores", year: 1929, genre_id: 1},
  {title: "Bailarin Compadrito", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: 1929, genre_id: 1},
  {title: "Bailarin De Contrasena", composer: "Victor Felice", lyricist: "Carlos Lucero", year: nil, genre_id: 1},
  {title: "Bailemos", composer: "Pascual Mamone", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Bajo El Cono Azul", composer: "Alfredo De Angelis", lyricist: "Carmelo Volpe", year: 1943, genre_id: 1},
  {title: "Bajo Un Cielo De Estrellas", composer: "Enrique Francini", lyricist: "Jose Maria Contursi", year: 1941, genre_id: 2},
  {title: "Balada Para Un Loco", composer: "Astor Piazzolla", lyricist: "Horacio Ferrer", year: 1969, genre_id: 1},
  {title: "Bandoneon Arrabalero", composer: "Bachicha", lyricist: "Pascual Contursi", year: 1928, genre_id: 1},
  {title: "Barajando Recuerdos", composer: "Luis Visca", lyricist: "Enrique Cadicamo", year: nil, genre_id: 1},
  {title: "Barrio De Tango", composer: "Anibal Troilo", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Bigotito", composer: "Edgardo Donato", lyricist: "Celedonio Flores", year: nil, genre_id: 5},
  {title: "Cada Vez Que Me Recuerdes", composer: "Mariano Mores", lyricist: "Jose Maria Contursi", year: 1943, genre_id: 1},
  {title: "Cafe De Los Angelitos", composer: "Jose Razzano / Catulo Castillo", lyricist: "Jose Razzano / Catulo Castillo", year: 1944, genre_id: 1},
  {title: "Cafetin De Buenos Aires", composer: "Mariano Mores", lyricist: "Enrique Santos Discepolo", year: 1948, genre_id: 1},
  {title: "Calla Bandoneon", composer: "Carlos Lazzari", lyricist: "Oscar Rubens", year: nil, genre_id: 1},
  {title: "Cambalache", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1934, genre_id: 1},
  {title: "Caminito", composer: "Juan De Dios Filiberto", lyricist: "Gabino Coria Penaloza", year: 1926, genre_id: 1},
  {title: "Campo Afuera", composer: "Rodolfo Biagi", lyricist: "Homero Manzi", year: 1939, genre_id: 3},
  {title: "Cancion De Rango (Pa Que Se Callen)", composer: "Raul Kaplun", lyricist: "Jose Maria Sune", year: 1942, genre_id: 1},
  {title: "Cancion Desesperada", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1945, genre_id: 1},
  {title: "Cantando", composer: "Mercedes Simone", lyricist: "Mercedes Simone", year: 1931, genre_id: 1},
  {title: "Caricias", composer: "Maria Isolina Godard", lyricist: "Juan Andres Caruso", year: nil, genre_id: 1},
  {title: "Carillon De La Merced", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo / Alfredo Le Pera", year: 1931, genre_id: 1},
  {title: "Carnaval De Mi Barrio", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1938, genre_id: 1},
  {title: "Cascabelito", composer: "Jose Bohr", lyricist: "Juan Andres Caruso", year: 1924, genre_id: 1},
  {title: "Chapaleando Barro", composer: "Arturo Castillo", lyricist: "Celedonio Flores", year: nil, genre_id: 1},
  {title: "Charlemos", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1940, genre_id: 1},
  {title: "Che Bandoneon", composer: "Anibal Troilo", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Chorra", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1928, genre_id: 1},
  {title: "Como Dos Extranos", composer: "Pedro Laurenz", lyricist: "Jose Maria Contursi", year: 1940, genre_id: 1},
  {title: "Como El Hornero", composer: "Manuel Sucher", lyricist: "Jose Rotulo", year: 1944, genre_id: 1},
  {title: "Compadron", composer: "Luis Visca", lyricist: "Enrique Cadicamo", year: 1927, genre_id: 1},
  {title: "Con Alma Y Vida", composer: "Carlos Di Sarli", lyricist: "Hector Marco", year: nil, genre_id: 3},
  {title: "Con Tus Besos", composer: "Santiago Ricci", lyricist: "Domingo Rosa", year: nil, genre_id: 2},
  {title: "Condena", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1937, genre_id: 1},
  {title: "Confesion", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1931, genre_id: 1},
  {title: "Convencernos", composer: "Eladia Blazquez", lyricist: "Eladia Blazquez", year: nil, genre_id: 1},
  {title: "Corazon", composer: "Carlos Di Sarli", lyricist: "Hector Marco", year: 1939, genre_id: 1},
  {title: "Corazon De Oro", composer: "Francisco Canaro", lyricist: "Jesus Fernandez Blanco", year: nil, genre_id: 2},
  {title: "Corazon, No Le Hagas Caso!", composer: "Armando Pontier", lyricist: "Carlos Bahr", year: 1943, genre_id: 1},
  {title: "Corrientes Y Esmeralda", composer: "Francisco Pracanico", lyricist: "Celedonio Flores", year: 1933, genre_id: 1},
  {title: "Cosas Olvidadas", composer: "Antonio Rodio", lyricist: "Jose Maria Contursi", year: 1940, genre_id: 1},
  {title: "Cristal", composer: "Mariano Mores", lyricist: "Jose Maria Contursi", year: 1944, genre_id: 1},
  {title: "Cualquier Cosa", composer: "Herminia Velich", lyricist: "Herminia Velich", year: 1927, genre_id: 1},
  {title: "Cuando Llegue El Invierno", composer: "Jose Marquez", lyricist: "Jose Marquez", year: 1948, genre_id: 1},
  {title: "Cuando No Se Quiere Mas", composer: "Roberto Rufino", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Cuando Un Viejo Se Enamora", composer: "Rodolfo Sciammarella", lyricist: "Manuel Romero", year: nil, genre_id: 3},
  {title: "Cuartito Azul", composer: "Mariano Mores", lyricist: "Mario Battistella", year: 1939, genre_id: 1},
  {title: "Cuatro Lagrimas", composer: "Lito Bayardo", lyricist: "Lito Bayardo", year: 1945, genre_id: 1},
  {title: "Cuatro Palabras", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: nil, genre_id: 2},
  {title: "Cuesta Abajo", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1934, genre_id: 1},
  {title: "Danza Maligna", composer: "Fernando Randle", lyricist: "Claudio Frollo", year: nil, genre_id: 1},
  {title: "De Mi Barrio", composer: "Roberto Goyheneche", lyricist: "Roberto Goyheneche", year: 1923, genre_id: 1},
  {title: "De Puro Curda", composer: "Carlos Olmedo", lyricist: "Abel Aznar", year: 1957, genre_id: 1},
  {title: "De Puro Guapo", composer: "Rafael Iriarte", lyricist: "Juan Carlos Fernandez Diaz", year: 1927, genre_id: 1},
  {title: "Decile Que Vuelva", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: nil, genre_id: 1},
  {title: "Dejame No Quiero Verte Mas", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: nil, genre_id: 1},
  {title: "Derrotado (Tenes Razon)", composer: "Antonio Arcieri", lyricist: "Jose Terragno", year: nil, genre_id: 1},
  {title: "Desde El Alma", composer: "Rosita Melo", lyricist: "Homero Manzi", year: 1947, genre_id: 2},
  {title: "Desencanto", composer: "Enrique Santos Discepolo", lyricist: "Luis Cesar Amadori", year: 1936, genre_id: 1},
  {title: "Desencuentro", composer: "Anibal Troilo", lyricist: "Catulo Castillo", year: 1962, genre_id: 1},
  {title: "Despues", composer: "Hugo Gutierrez", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Destellos", composer: "Francisco Canaro", lyricist: "Juan Andres Caruso", year: 1924, genre_id: 1},
  {title: "Dime Mi Amor", composer: "Rodolfo Sciammarella", lyricist: "Manuel Romero", year: nil, genre_id: 1},
  {title: "Din Don", composer: "Alberto Suarez Villanueva", lyricist: "Evaristo Fratantoni", year: nil, genre_id: 1},
  {title: "Donde Estas Corazon", composer: "Luis Martinez Serrano", lyricist: "Luis Martinez Serrano", year: 1930, genre_id: 1},
  {title: "Duelo Criollo", composer: "Juan Rezzano", lyricist: "Lito Bayardo", year: 1928, genre_id: 1},
  {title: "El Abrojito", composer: "Luis Bernstein", lyricist: "Jesus Fernandez Blanco", year: 1926, genre_id: 1},
  {title: "El Adios", composer: "Maruja Pacheco Huergo", lyricist: "Virgilio San Clemente", year: 1937, genre_id: 1},
  {title: "El Choclo", composer: "Angel Villoldo", lyricist: "Enrique Santos Discepolo", year: nil, genre_id: 1},
  {title: "El Ciruja", composer: "Ernesto De La Cruz", lyricist: "Alfredo Marino", year: 1926, genre_id: 1},
  {title: "El Dia Que Me Quieras", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 6},
  {title: "El Firulete", composer: "Mariano Mores", lyricist: "Rodolfo Taboada", year: nil, genre_id: 3},
  {title: "El Fueye De Arolas", composer: "Hector Marco", lyricist: "Hector Marco", year: nil, genre_id: 1},
  {title: "El Huracan", composer: "Osvaldo Donato", lyricist: "Nolo Lopez", year: nil, genre_id: 1},
  {title: "El Motivo", composer: "Juan Carlos Cobian", lyricist: "Pascual Contursi", year: nil, genre_id: 1},
  {title: "El Olivo", composer: "Antonio Scatasso", lyricist: "Carlos Cabral", year: 1924, genre_id: 1},
  {title: "El Panuelito", composer: "Juan De Dios Filiberto", lyricist: "Gabino Coria Penaloza", year: 1920, genre_id: 1},
  {title: "El Vals Sonador", composer: "Armando Pontier", lyricist: "Oscar Rubens", year: nil, genre_id: 2},
  {title: "El Yacare", composer: "Alfredo Attadia", lyricist: "Mario Soto", year: nil, genre_id: 1},
  {title: "El ultimo Cafe", composer: "Hector Stamponi", lyricist: "Catulo Castillo", year: nil, genre_id: 1},
  {title: "El ultimo Organito", composer: "Acho Manzi", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Embrujamiento", composer: "Ricardo Malerba", lyricist: "Manuel Ferradas Campos", year: nil, genre_id: 1},
  {title: "En Carne Propia", composer: "Manuel Sucher", lyricist: "Carlos Bahr", year: 1944, genre_id: 1},
  {title: "En Esta Tarde Gris", composer: "Mariano Mores", lyricist: "Jose Maria Contursi", year: 1941, genre_id: 1},
  {title: "En La Buena Y En La Mala", composer: "Domingo Scarpino", lyricist: "Enrique Cadicamo", year: nil, genre_id: 1},
  {title: "En Tus Brazos", composer: "Carlos Zarate", lyricist: "Marvil (Elizardo Martinez Vilas)", year: nil, genre_id: 1},
  {title: "Entre Pitada Y Pitada", composer: "Rodolfo Sciammarella", lyricist: "Rodolfo Sciammarella", year: nil, genre_id: 3},
  {title: "Esquinas Portenas", composer: "Sebastian Piana", lyricist: "Homero Manzi", year: 1933, genre_id: 2},
  {title: "Esta Noche Al Pasar", composer: "Hector Grane", lyricist: "Justo Ricardo Thompson", year: 1945, genre_id: 1},
  {title: "Esta Noche De Luna", composer: "Jose Garcia", lyricist: "Hector Marco", year: 1943, genre_id: 1},
  {title: "Esta Noche En Buenos Aires", composer: "Angel D'agostino", lyricist: "Avlis (Erasmo Silva Cabrera)", year: 1944, genre_id: 1},
  {title: "Esta Noche Me Emborracho", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1928, genre_id: 1},
  {title: "Estampa Federal", composer: "Pedro Maffia", lyricist: "Catulo Castillo", year: nil, genre_id: 2},
  {title: "Este Es Tu Tango", composer: "Enrique Mora", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Farol", composer: "Virgilio Exposito", lyricist: "Homero Exposito", year: 1943, genre_id: 1},
  {title: "Flor De Lino", composer: "Hector Stamponi", lyricist: "Homero Exposito", year: 1947, genre_id: 6},
  {title: "Flores Del Alma", composer: "Juan Larenza", lyricist: "Alfredo Lucero Palacios", year: nil, genre_id: 2},
  {title: "Fuimos", composer: "Jose Dames", lyricist: "Homero Manzi", year: 1945, genre_id: 1},
  {title: "Fumando Espero", composer: "Juan Viladomat", lyricist: "Felix Garzo", year: 1922, genre_id: 1},
  {title: "Garganta Con Arena", composer: "Cacho Castana", lyricist: "Cacho Castana", year: 1993, genre_id: 1},
  {title: "Garua", composer: "Anibal Troilo", lyricist: "Enrique Cadicamo", year: 1943, genre_id: 1},
  {title: "Gitana Rusa", composer: "Juan Sanchez Gorio", lyricist: "Horacio Sanguinetti", year: 1942, genre_id: 1},
  {title: "Golgota", composer: "Rodolfo Biagi", lyricist: "Francisco Gorrindo", year: 1938, genre_id: 1},
  {title: "Gricel", composer: "Mariano Mores", lyricist: "Jose Maria Contursi", year: 1942, genre_id: 1},
  {title: "Griseta", composer: "Enrique Delfino", lyricist: "Jose Gonzalez Castillo", year: 1924, genre_id: 1},
  {title: "Hasta Siempre Amor", composer: "Donato Racciatti", lyricist: "Federico Silva", year: 1953, genre_id: 1},
  {title: "Hay Que Vivirla Compadre", composer: "Angel Dagostino", lyricist: "Hector Marco", year: nil, genre_id: 1},
  {title: "Historia De Un Amor", composer: "Carlos Almaran", lyricist: "Carlos Almaran", year: nil, genre_id: 6},
  {title: "Humillacion", composer: "Rodolfo Biagi", lyricist: "Carlos Bahr", year: 1941, genre_id: 1},
  {title: "Ilusion Azul", composer: "Arquimedes Arci", lyricist: "Arquimedes Arci", year: nil, genre_id: 2},
  {title: "Infamia", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1941, genre_id: 1},
  {title: "Inutil", composer: "Tito Ribero", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Jacinto Chiclana", composer: "Astor Piazzolla", lyricist: "Jorge Luis Borges", year: nil, genre_id: 3},
  {title: "Jamas Retornaras", composer: "Osmar Maderna", lyricist: "Osmar Maderna", year: 1942, genre_id: 1},
  {title: "Junto A Tu Corazon", composer: "Enrique Francini", lyricist: "Jose Maria Contursi", year: 1942, genre_id: 1},
  {title: "La Abandone Y No Sabia", composer: "Jose Canet", lyricist: "Jose Canet", year: 1943, genre_id: 1},
  {title: "La Bicicleta Blanca", composer: "Astor Piazzolla", lyricist: "Horacio Ferrer", year: nil, genre_id: 6},
  {title: "La Bruja", composer: "Juan Polito", lyricist: "Francisco Gorrindo", year: 1938, genre_id: 1},
  {title: "La Cachila", composer: "Eduardo Arolas", lyricist: "Hector Polito", year: nil, genre_id: 1},
  {title: "La Cancion De Buenos Aires", composer: "Orestes Cufaro", lyricist: "Manuel Romero", year: 1933, genre_id: 1},
  {title: "La Capilla Blanca", composer: "Carlos Di Sarli", lyricist: "Hector Marco", year: 1944, genre_id: 1},
  {title: "La Casita De Mis Viejos", composer: "Juan Carlos Cobian", lyricist: "Enrique Cadicamo", year: 1932, genre_id: 1},
  {title: "La Copa Del Olvido", composer: "Enrique Delfino", lyricist: "Alberto Vacarezza", year: 1921, genre_id: 1},
  {title: "La Cumparsita", composer: "Gerardo Matos Rodriguez", lyricist: "Pascual Contursi / Enrique Maroni", year: nil, genre_id: 1},
  {title: "La Mariposa", composer: "Pedro Maffia", lyricist: "Celedonio Flores", year: 1923, genre_id: 1},
  {title: "La Melodia Del Corazon", composer: "Fioravante Di Cicco", lyricist: "Carmelo Santiago", year: nil, genre_id: 1},
  {title: "La Milonga De Buenos Aires", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1939, genre_id: 3},
  {title: "La Morocha", composer: "Enrique Saborido", lyricist: "Angel Villoldo", year: 1905, genre_id: 1},
  {title: "La Mulateada", composer: "Julio Eduardo Del Puerto", lyricist: "Carlos Pesce", year: nil, genre_id: 3},
  {title: "La Piba De Los Jazmines", composer: "Ricardo Malerba", lyricist: "Julio Navarrine", year: nil, genre_id: 1},
  {title: "La Ultima Copa", composer: "Francisco Canaro", lyricist: "Juan Andres Caruso", year: 1926, genre_id: 1},
  {title: "La Ultima Curda", composer: "Anibal Troilo", lyricist: "Catulo Castillo", year: 1956, genre_id: 1},
  {title: "La Vida Es Corta", composer: "Ricardo Tanturi", lyricist: "Francisco Gorrindo", year: nil, genre_id: 1},
  {title: "Lejos De Buenos Aires", composer: "Alberto Suarez Villanueva", lyricist: "Oscar Rubens", year: 1942, genre_id: 1},
  {title: "Lilian", composer: "Hector Varela", lyricist: "Luis Caruso", year: 1944, genre_id: 1},
  {title: "Lloran Las Campanas", composer: "Alberto Suarez Villanueva", lyricist: "Oscar Rubens", year: 1944, genre_id: 1},
  {title: "Llorar Por Una Mujer", composer: "Enrique Rodriguez", lyricist: "Enrique Cadicamo", year: nil, genre_id: 1},
  {title: "Lo Han Visto Con Otra", composer: "Horacio Pettorossi", lyricist: "Horacio Pettorossi", year: 1928, genre_id: 1},
  {title: "Lo Pasao Paso", composer: "Miguel Eusebio Bucino", lyricist: "Miguel Eusebio Bucino", year: nil, genre_id: 1},
  {title: "Lo Que Vos Te Mereces", composer: "Carlos Olmedo", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Los Mareados (De Mi Pasado)", composer: "Juan Carlos Cobian", lyricist: "Enrique Cadicamo", year: 1942, genre_id: 1},
  {title: "Lunes", composer: "Jose Luis Padula", lyricist: "Francisco Garcia Jimenez", year: 1927, genre_id: 1},
  {title: "Madame Ivonne", composer: "Eduardo Pereyra", lyricist: "Enrique Cadicamo", year: 1933, genre_id: 1},
  {title: "Madreselva", composer: "Francisco Canaro", lyricist: "Luis Cesar Amadori", year: 1931, genre_id: 1},
  {title: "Malena", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1941, genre_id: 1},
  {title: "Malevaje", composer: "Juan De Dios Filiberto", lyricist: "Enrique Santos Discepolo", year: 1929, genre_id: 1},
  {title: "Manana Zarpa Un Barco", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Mandria", composer: "Juan Rodriguez", lyricist: "Francisco Brancatti", year: nil, genre_id: 1},
  {title: "Mano A Mano", composer: "Carlos Gardel", lyricist: "Celedonio Flores", year: 1923, genre_id: 1},
  {title: "Maquillaje", composer: "Virgilio Exposito", lyricist: "Homero Exposito", year: nil, genre_id: 1},
  {title: "Marioneta", composer: "Juan Jose Guichandut", lyricist: "Armando Tagini", year: 1928, genre_id: 1},
  {title: "Mariposita", composer: "Anselmo Aieta", lyricist: "Francisco Garcia Jimenez", year: 1941, genre_id: 1},
  {title: "Marol", composer: "Alberto Nery", lyricist: "Federico Silva", year: nil, genre_id: 1},
  {title: "Maula", composer: "Adolfo Mondino", lyricist: "Victor Solino", year: 1927, genre_id: 1},
  {title: "Me Quede Mirandola", composer: "Vicente Spina", lyricist: "Roberto Miro", year: 1945, genre_id: 1},
  {title: "Mendocina", composer: "Miguel Bruno", lyricist: "Benigno Palmeiro", year: nil, genre_id: 2},
  {title: "Metido (Enamorado)", composer: "Principe Cubano", lyricist: "Principe Cubano", year: nil, genre_id: 1},
  {title: "Mi Buenos Aires Querido", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1934, genre_id: 1},
  {title: "Mi Dolor", composer: "Carlos Marcucci", lyricist: "Manuel Meanos", year: 1930, genre_id: 1},
  {title: "Mi Noche Triste (Lita)", composer: "Samuel Castriota", lyricist: "Pascual Contursi", year: 1916, genre_id: 1},
  {title: "Mi Serenata", composer: "Edgardo Donato", lyricist: "Juan Carlos Thorry", year: nil, genre_id: 1},
  {title: "Mi Taza De Cafe", composer: "Alfredo Malerba", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Milonga Que Peina Canas", composer: "Alberto Gomez", lyricist: "Alberto Gomez", year: 1942, genre_id: 3},
  {title: "Milonga Querida", composer: "Juan Larenza", lyricist: "Lito Bayardo", year: nil, genre_id: 3},
  {title: "Milonga Triste", composer: "Sebastian Piana", lyricist: "Homero Manzi", year: 1936, genre_id: 3},
  {title: "Milonguita (Esthercita)", composer: "Enrique Delfino", lyricist: "Samuel Linnig", year: 1920, genre_id: 1},
  {title: "Mis Harapos (Caballero Del Ensueno)", composer: "Alberto Ghiraldo Albornoz ", lyricist: "Marino Garcia", year: nil, genre_id: 5},
  {title: "Moneda De Cobre", composer: "Carlos Vivan", lyricist: "Horacio Sanguinetti", year: 1942, genre_id: 1},
  {title: "Muchacho", composer: "Edgardo Donato", lyricist: "Celedonio Flores", year: 1926, genre_id: 1},
  {title: "Muchachos Comienza La Ronda", composer: "Luis Porcell", lyricist: "Leopoldo Diaz Velez", year: 1943, genre_id: 1},
  {title: "Muneca Brava", composer: "Luis Visca", lyricist: "Enrique Cadicamo", year: 1929, genre_id: 1},
  {title: "Murio El Malevo", composer: "Hector Varela", lyricist: "Carlos Waiss", year: nil, genre_id: 1},
  {title: "Nada", composer: "Jose Dames", lyricist: "Horacio Sanguinetti", year: nil, genre_id: 1},
  {title: "Nada Mas", composer: "Juan Darienzo", lyricist: "Juan Darienzo", year: 1938, genre_id: 1},
  {title: "Naranjo En Flor", composer: "Virgilio Exposito", lyricist: "Homero Exposito", year: 1944, genre_id: 1},
  {title: "Nido Gaucho", composer: "Carlos Di Sarli", lyricist: "Hector Marco", year: 1942, genre_id: 1},
  {title: "Niebla Del Riachuelo", composer: "Juan Carlos Cobian", lyricist: "Enrique Cadicamo", year: 1937, genre_id: 1},
  {title: "Ninguna", composer: "Raul Fernandez Siro", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Nino Bien", composer: "Juan Antonio Collazo", lyricist: "Victor Solino", year: 1928, genre_id: 1},
  {title: "No Hay Tierra Como La Mia", composer: "Charlo", lyricist: "Enrique Cadicamo", year: nil, genre_id: 3},
  {title: "No Me Escribas", composer: "Agustin Bardi", lyricist: "Juan Andres Caruso", year: 1927, genre_id: 1},
  {title: "No Me Pregunten Por Que", composer: "Carlos Di Sarli", lyricist: "Reynaldo Pignataro", year: 1935, genre_id: 1},
  {title: "No Mientas", composer: "Hector Varela", lyricist: "Hector Marco", year: nil, genre_id: 1},
  {title: "No Te Apures, Carablanca", composer: "Roberto Garza", lyricist: "Carlos Bahr", year: 1942, genre_id: 1},
  {title: "Noche De Reyes", composer: "Pedro Maffia", lyricist: "Jorge Curi", year: 1926, genre_id: 1},
  {title: "Nostalgias", composer: "Juan Carlos Cobian", lyricist: "Enrique Cadicamo", year: 1936, genre_id: 1},
  {title: "Nunca Tuvo Novio", composer: "Agustin Bardi", lyricist: "Enrique Cadicamo", year: 1930, genre_id: 1},
  {title: "Oigo Tu Voz", composer: "Mario Canaro", lyricist: "Francisco Garcia Jimenez", year: nil, genre_id: 1},
  {title: "Ojos Negros Que Fascinan", composer: "Manuel Salina", lyricist: "Florian Rey", year: nil, genre_id: 1},
  {title: "Olvidao", composer: "Guillermo Barbieri", lyricist: "Enrique Cadicamo", year: 1932, genre_id: 1},
  {title: "Oro Y Plata", composer: "Charlo", lyricist: "Homero Manzi", year: 1943, genre_id: 3},
  {title: "Pa Que Seguir", composer: "Francisco Fiorentino", lyricist: "Pedro Lloret", year: nil, genre_id: 1},
  {title: "Paciencia", composer: "Juan Darienzo", lyricist: "Francisco Gorrindo", year: 1937, genre_id: 1},
  {title: "Paisaje", composer: "Sebastian Piana", lyricist: "Homero Manzi", year: 1943, genre_id: 2},
  {title: "Pajaro Ciego", composer: "Antonio Bonavena", lyricist: "Lito Bayardo", year: nil, genre_id: 1},
  {title: "Pasional", composer: "Jorge Caldara", lyricist: "Mario Soto", year: 1951, genre_id: 1},
  {title: "Patotero Sentimental", composer: "Manuel Joves", lyricist: "Manuel Romero", year: 1922, genre_id: 1},
  {title: "Pensalo Bien", composer: "Alberto Calvera", lyricist: "Enrique Lopez", year: nil, genre_id: 1},
  {title: "Percal", composer: "Domingo Federico", lyricist: "Homero Exposito", year: 1943, genre_id: 1},
  {title: "Pero Yo Se", composer: "Azucena Maizani", lyricist: "Azucena Maizani", year: 1928, genre_id: 1},
  {title: "Pobre Flor (Primera Ilusion)", composer: "Luis Mottolese", lyricist: "Victor Spindola", year: nil, genre_id: 2},
  {title: "Pocas Palabras", composer: "Ricardo Tanturi", lyricist: "Enrique Cadicamo", year: 1941, genre_id: 1},
  {title: "Poema", composer: "Eduardo Bianco / Mario Melfi", lyricist: "Mario Melfi / Eduardo Bianco", year: nil, genre_id: 1},
  {title: "Por Que Canto Asi", composer: "Jose Razzano", lyricist: "Celedonio Flores", year: 1943, genre_id: 1},
  {title: "Por Que La Quise Tanto", composer: "Mariano Mores", lyricist: "Rodolfo Taboada", year: nil, genre_id: 1},
  {title: "Por Una Cabeza", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Prohibido", composer: "Manuel Sucher", lyricist: "Carlos Bahr", year: nil, genre_id: 1},
  {title: "Que Bien Te Queda (Como Has Cambiado)", composer: "Vicente Salerno", lyricist: "Juan Mazaroni", year: 1944, genre_id: 1},
  {title: "Que Falta Que Me Haces", composer: "Armando Pontier", lyricist: "Federico Silva", year: nil, genre_id: 1},
  {title: "Que No Sepan Las Estrellas", composer: "Jose Ranieri", lyricist: "Alfredo Faustino Roldan", year: 1945, genre_id: 1},
  {title: "Que Nunca Me Falte", composer: "Hector Morales", lyricist: "Hector Marco", year: 1937, genre_id: 1},
  {title: "Que Se Vayan", composer: "Francisco Canosa", lyricist: "Enrique Dizeo", year: 1929, genre_id: 1},
  {title: "Que Sera De Ti", composer: "Roberto Nievas Blanco", lyricist: "Julio Jorge Nelson", year: nil, genre_id: 1},
  {title: "Que Tango Hay Que Cantar", composer: "Ruben Juarez", lyricist: "Cacho Castana", year: nil, genre_id: 1},
  {title: "Que Te Importa Que Te Llore", composer: "Miguel Calo", lyricist: "Miguel Calo", year: 1942, genre_id: 1},
  {title: "Quiero Verte Una Vez Mas", composer: "Mario Canaro", lyricist: "Jose Maria Contursi", year: 1939, genre_id: 1},
  {title: "Recien", composer: "Osvaldo Pugliese", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Recuerdo Malevo", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1933, genre_id: 1},
  {title: "Recuerdos De La Pampa", composer: "Rodolfo Duclos", lyricist: "Rodolfo Duclos", year: nil, genre_id: 2},
  {title: "Remembranza", composer: "Mario Melfi", lyricist: "Mario Battistella", year: 1934, genre_id: 1},
  {title: "Rie Payaso", composer: "Virgilio Carmona", lyricist: "Emilio Falero", year: 1929, genre_id: 1},
  {title: "Romance De Barrio", composer: "Anibal Troilo", lyricist: "Homero Manzi", year: 1947, genre_id: 2},
  {title: "Rondando Tu Esquina", composer: "Charlo", lyricist: "Enrique Cadicamo", year: 1945, genre_id: 1},
  {title: "Rosas De Otono", composer: "Pedro De Toro", lyricist: "Pedro De Toro", year: 1939, genre_id: 2},
  {title: "Se Dice De Mi", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1943, genre_id: 3},
  {title: "Se Lustra Senor", composer: "Enrique Alessio", lyricist: "Marvil (Elizardo Martinez Vilas)", year: 1946, genre_id: 1},
  {title: "Senores Yo Soy Del Centro", composer: "Armando Baliotti", lyricist: "Santiago Adamini", year: nil, genre_id: 3},
  {title: "Siempre Es Carnaval", composer: "Osvaldo Fresedo", lyricist: "Emilio Fresedo", year: 1937, genre_id: 1},
  {title: "Silbando", composer: "Sebastian Piana / Catulo Castillo", lyricist: "Jose Gonzalez Castillo", year: 1925, genre_id: 1},
  {title: "Silencio", composer: "Carlos Gardel / Horacio Pettorossi", lyricist: "Alfredo Le Pera / Horacio Pettorossi", year: 1932, genre_id: 1},
  {title: "Sin Palabras", composer: "Mariano Mores", lyricist: "Enrique Santos Discepolo", year: 1946, genre_id: 1},
  {title: "Sin Rumbo Fijo", composer: "Eugenio Carrere / Hermes Peressini", lyricist: "Eugenio Carrere / Hermes Peressini", year: nil, genre_id: 1},
  {title: "Solamente Ella", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Sonar Y Nada Mas", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1943, genre_id: 2},
  {title: "Sosiego En La Noche", composer: "Roberto Garza", lyricist: "Carlos Bahr", year: 1943, genre_id: 1},
  {title: "Soy Aquel Viajero", composer: "Hector Grane", lyricist: "Justo Ricardo Thompson", year: nil, genre_id: 1},
  {title: "Sus Ojos Se Cerraron", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Tabernero (El Tabernero)", composer: "Fausto Frontera", lyricist: "Raul Costa Oliveri", year: 1927, genre_id: 1},
  {title: "Tal Vez Sera Su Voz", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Te Aconsejo Que Me Olvides", composer: "Pedro Maffia", lyricist: "Jorge Curi", year: 1926, genre_id: 1},
  {title: "Tinta Roja", composer: "Sebastian Piana", lyricist: "Catulo Castillo", year: 1941, genre_id: 1},
  {title: "Toda Mi Vida", composer: "Anibal Troilo", lyricist: "Jose Maria Contursi", year: 1941, genre_id: 1},
  {title: "Todo", composer: "Hugo Gutierrez", lyricist: "Homero Exposito", year: nil, genre_id: 1},
  {title: "Todo Te Nombra", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: nil, genre_id: 1},
  {title: "Tomo Y Obligo", composer: "Carlos Gardel", lyricist: "Manuel Romero", year: 1931, genre_id: 1},
  {title: "Tormenta", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1939, genre_id: 1},
  {title: "Torrente", composer: "Hugo Gutierrez", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Trasnochando", composer: "Armando Baliotti", lyricist: "Santiago Adamini", year: 1942, genre_id: 1},
  {title: "Tres Amigos", composer: "Enrique Cadicamo", lyricist: "Enrique Cadicamo", year: 1944, genre_id: 1},
  {title: "Tres Esquinas", composer: "Angel Dagostino", lyricist: "Enrique Cadicamo", year: 1941, genre_id: 1},
  {title: "Triste Comedia", composer: "Hector Stamponi", lyricist: "Oscar Rubens", year: 1949, genre_id: 1},
  {title: "Tristeza Marina", composer: "Jose Dames", lyricist: "Horacio Sanguinetti", year: 1943, genre_id: 1},
  {title: "Tu Angustia Y Mi Dolor", composer: "Alfredo Gobbi", lyricist: "Julio Camilloni", year: nil, genre_id: 1},
  {title: "Tu Boca Mintio", composer: "Armando Angeletti", lyricist: "Alberto Longo", year: nil, genre_id: 1},
  {title: "Tu Diagnostico", composer: "Jose Betinotti", lyricist: "Jose Betinotti", year: nil, genre_id: 2},
  {title: "Tu El Cielo Y Tu", composer: "Mario Canaro", lyricist: "Hector Marco", year: 1944, genre_id: 1},
  {title: "Tu Vieja Ventana", composer: "Guillermo Barbieri", lyricist: "Ambrosio Rio", year: nil, genre_id: 2},
  {title: "Tus Labios Me Diran", composer: "Emilio Brameri", lyricist: "Hector Negro", year: nil, genre_id: 1},
  {title: "Un Crimen", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: nil, genre_id: 1},
  {title: "Una Emocion", composer: "Raul Kaplun", lyricist: "Jose Maria Sune", year: 1943, genre_id: 1},
  {title: "Una Lagrima Tuya", composer: "Mariano Mores", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Una Noche De Garufa", composer: "Eduardo Arolas", lyricist: "Gabriel Clausi", year: nil, genre_id: 1},
  {title: "Una Pena", composer: "Adolfo Rosquellas", lyricist: "Arturo Albert", year: 1923, genre_id: 1},
  {title: "Una Piba Como Vos", composer: "Dante Gilardoni", lyricist: "Dante Gilardoni", year: nil, genre_id: 1},
  {title: "Uno ", composer: "Mariano Mores", lyricist: "Enrique Santos Discepolo", year: nil, genre_id: 1},
  {title: "Vamos", composer: "Feliciano Brunelli", lyricist: "Rodolfo Sciammarella", year: 1944, genre_id: 1},
  {title: "Ventanita De Arrabal", composer: "Antonio Scatasso", lyricist: "Pascual Contursi", year: 1927, genre_id: 1},
  {title: "Ventarron", composer: "Pedro Maffia", lyricist: "Jose Horacio Staffolani", year: 1933, genre_id: 1},
  {title: "Verdemar", composer: "Carlos Di Sarli", lyricist: "Jose Maria Contursi", year: 1943, genre_id: 1},
  {title: "Vida Mia", composer: "Osvaldo Fresedo", lyricist: "Emilio Fresedo", year: 1933, genre_id: 1},
  {title: "Vieja Recova", composer: "Rodolfo Sciammarella", lyricist: "Enrique Cadicamo", year: 1930, genre_id: 1},
  {title: "Viejo Porton", composer: "Hector Palacios", lyricist: "Maximo Orsi", year: nil, genre_id: 2},
  {title: "Violin", composer: "Ricardo Malerba / Dante Smurra", lyricist: "Horacio Sanguinetti", year: nil, genre_id: 1},
  {title: "Volve Mi Negra", composer: "Jose Maria Rizzuti", lyricist: "Jose Diez Gomez", year: nil, genre_id: 1},
  {title: "Volver", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Volver A Vernos", composer: "Joaquin Mora", lyricist: "Luis Castineira", year: nil, genre_id: 1},
  {title: "Vuelves", composer: "Maria Esther Pacheco Huergo", lyricist: "Virgilio San Clemente", year: 1939, genre_id: 1},
  {title: "Vuelvo Al Sur", composer: "Astor Piazzolla", lyricist: "Fernando \"Pino\" Solanas", year: nil, genre_id: 1},
  {title: "Whisky", composer: "Hector Marco", lyricist: "Hector Marco", year: 1957, genre_id: 1},
  {title: "Y Todavia Te Quiero", composer: "Luciano Leocata", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Ya Sale El Tren", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1943, genre_id: 1},
  {title: "Yira Yira", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1930, genre_id: 1},
  {title: "Yo Me Llamo Juan Te Quiero", composer: "Antonio Molina", lyricist: "Fernan Silva Valdes", year: nil, genre_id: 3},
  {title: "Yo No Se Que Me Han Hecho Tus Ojos", composer: "Francisco Canaro", lyricist: "Francisco Canaro", year: nil, genre_id: 2},
  {title: "Yo Soy De San Telmo", composer: "Arturo Gallucci", lyricist: "Victorino Velazquez", year: nil, genre_id: 3},
  {title: "Yo Tambien Sone", composer: "Francisco Canaro", lyricist: "Luis Cesar Amadori", year: 1935, genre_id: 1},
  {title: "Yo Te Adoro Bandoneon", composer: "Ramon Coll", lyricist: "Carlos Pesce", year: nil, genre_id: 1},
  {title: "Yuyo Verde", composer: "Domingo Federico", lyricist: "Homero Exposito", year: 1944, genre_id: 1},
  {title: "Zapatitos De Raso", composer: "Jorge Dragone", lyricist: "Fernando Caprio", year: nil, genre_id: 3},
  {title: "Zorzal", composer: "Dorita Zarate", lyricist: "Dorita Zarate", year: nil, genre_id: 3}
])
Translation.create!([
  {link: "http://www.eltangoteespera.com/2013/06/pa-que-seguir.html", song_id: 211},
  {link: "http://www.eltangoteespera.com/2013/06/vuelves.html", song_id: 294},
  {link: "http://www.eltangoteespera.com/2013/06/que-sera-de-ti.html", song_id: 232},
  {link: "http://www.eltangoteespera.com/2013/03/no-te-apures-carablanca.html", song_id: 204},
  {link: "http://www.eltangoteespera.com/2013/03/cascabelito.html", song_id: 47},
  {link: "http://www.eltangoteespera.com/2013/03/tal-vez-sera-su-voz-tal-vez-sera-el.html", song_id: 257},
  {link: "http://www.eltangoteespera.com/2013/02/con-tus-besos.html", song_id: 307},
  {link: "http://www.eltangoteespera.com/2013/01/embrujamiento.html", song_id: 102},
  {link: "http://www.eltangoteespera.com/2012/12/esta-noche-en-buenos-aires.html", song_id: 111},
  {link: "http://www.eltangoteespera.com/2012/11/vieja-recova.html", song_id: 287},
  {link: "http://www.eltangoteespera.com/2012/11/no-me-escribas.html", song_id: 201},
  {link: "http://www.eltangoteespera.com/2012/11/que-no-sepan-las-estrellas.html", song_id: 229},
  {link: "http://www.eltangoteespera.com/2012/11/destellos.html", song_id: 83},
  {link: "http://www.eltangoteespera.com/2012/11/golgota.html", song_id: 124},
  {link: "http://www.eltangoteespera.com/2012/10/pajaro-ciego.html", song_id: 213},
  {link: "http://www.eltangoteespera.com/2012/10/recuerdos-de-la-pampa.html", song_id: 238},
  {link: "http://www.eltangoteespera.com/2012/10/mi-taza-de-cafe.html", song_id: 183},
  {link: "http://www.eltangoteespera.com/2012/10/senores-yo-soy-del-centro.html", song_id: 245},
  {link: "http://www.eltangoteespera.com/2012/10/sin-rumbo-fijo.html", song_id: 250},
  {link: "http://www.eltangoteespera.com/2012/09/el-huracan.html", song_id: 94},
  {link: "http://www.eltangoteespera.com/2012/09/rie-payaso.html", song_id: 240},
  {link: "http://www.eltangoteespera.com/2012/09/ventanita-de-arrabal.html", song_id: 283},
  {link: "http://www.eltangoteespera.com/2012/09/nada.html", song_id: 308},
  {link: "http://www.eltangoteespera.com/2012/09/todo.html", song_id: 309},
  {link: "http://www.eltangoteespera.com/2012/09/cafe-de-los-angelitos.html", song_id: 35},
  {link: "http://www.eltangoteespera.com/2012/09/tres-amigos.html", song_id: 266},
  {link: "http://www.eltangoteespera.com/2012/09/carillon-de-la-merced.html", song_id: 45},
  {link: "http://www.eltangoteespera.com/2012/09/ojos-negros-que-fascinan.html", song_id: 310},
  {link: "http://www.eltangoteespera.com/2012/09/tormenta.html", song_id: 263},
  {link: "http://www.eltangoteespera.com/2012/08/entre-pitada-y-pitada.html", song_id: 107},
  {link: "http://www.eltangoteespera.com/2012/08/mis-harapos-caballero-del-ensueno.html", song_id: 188},
  {link: "http://www.eltangoteespera.com/2012/08/tu-vieja-ventana.html", song_id: 274},
  {link: "http://www.eltangoteespera.com/2012/07/enamorado-metido.html", song_id: 178},
  {link: "http://www.eltangoteespera.com/2012/06/lo-pasao-paso.html", song_id: 311},
  {link: "http://www.eltangoteespera.com/2012/03/alma-de-bohemio.html", song_id: 15},
  {link: "http://www.eltangoteespera.com/2012/03/la-luz-del-candil.html", song_id: 1},
  {link: "http://www.eltangoteespera.com/2012/03/todo-te-nombra.html", song_id: 261},
  {link: "http://www.eltangoteespera.com/2012/03/rosas-de-otono.html", song_id: 312},
  {link: "http://www.eltangoteespera.com/2012/02/la-piba-de-los-jazmines.html", song_id: 152},
  {link: "http://www.eltangoteespera.com/2012/02/alma-mia.html", song_id: 16},
  {link: "http://www.eltangoteespera.com/2012/01/gitana-rusa.html", song_id: 123},
  {link: "http://www.eltangoteespera.com/2012/01/paciencia.html", song_id: 212},
  {link: "http://www.eltangoteespera.com/2012/01/caminito.html", song_id: 39},
  {link: "http://www.eltangoteespera.com/2012/01/marioneta.html", song_id: 172},
  {link: "http://www.eltangoteespera.com/2012/01/yo-tambien-sone.html", song_id: 302},
  {link: "http://www.eltangoteespera.com/2011/12/danza-maligna.html", song_id: 72},
  {link: "http://www.eltangoteespera.com/2011/09/cuatro-lagrimas.html", song_id: 69},
  {link: "http://www.eltangoteespera.com/2011/06/patotero-sentimental.html", song_id: 216},
  {link: "http://www.eltangoteespera.com/2011/05/milonga-querida.html", song_id: 185},
  {link: "http://www.eltangoteespera.com/2011/05/no-hay-tierra-como-la-mia.html", song_id: 200},
  {link: "http://www.eltangoteespera.com/2011/04/la-vida-es-corta.html", song_id: 155},
  {link: "http://www.eltangoteespera.com/2011/04/uno.html", song_id: 313},
  {link: "http://www.eltangoteespera.com/2011/04/pensalo-bien.html", song_id: 217},
  {link: "http://www.eltangoteespera.com/2011/04/no-mientas.html", song_id: 203},
  {link: "http://www.eltangoteespera.com/2011/04/este-es-tu-tango.html", song_id: 114},
  {link: "http://www.eltangoteespera.com/2011/03/barajando-recuerdos.html", song_id: 31},
  {link: "http://www.eltangoteespera.com/2011/03/corazon.html", song_id: 59},
  {link: "http://www.eltangoteespera.com/2011/02/duelo-criollo.html", song_id: 87},
  {link: "http://www.eltangoteespera.com/2011/02/corazon-de-oro.html", song_id: 60},
  {link: "http://www.eltangoteespera.com/2011/01/pobre-flor.html", song_id: 220},
  {link: "http://www.eltangoteespera.com/2011/01/los-mareados.html", song_id: 162},
  {link: "http://www.eltangoteespera.com/2011/01/con-alma-y-vida.html", song_id: 55},
  {link: "http://www.eltangoteespera.com/2011/01/muneca-brava.html", song_id: 192},
  {link: "http://www.tangodc.com/lyrics/lopasaopaso.htm", song_id: 311}
])
