Genre.create!([
  {name: "Tango"},
  {name: "Vals"},
  {name: "Milonga"},
  {name: "Candombe"},
  {name: "Foxtrot"},
  {name: "Otros Ritmos"}
])
Song.create!([
  {title: "A La Luz Del Candil", composer: "Carlos Vicente Geroni Flores", lyricist: "Julio Navarrine", year: 1927, genre_id: 1},
  {title: "A Media Luz", composer: "Edgardo Donato", lyricist: "Carlos Lenzi", year: 1924, genre_id: 1},
  {title: "A Mi Madre", composer: "Carlos Gardel", lyricist: "Andrés Cepeda", year: nil, genre_id: 2},
  {title: "Abandono", composer: "Pedro Maffia", lyricist: "Homero Manzi", year: nil, genre_id: 1},
  {title: "Acquaforte", composer: "Horacio Pettorossi", lyricist: "Juan Carlos Marambio Catán", year: 1932, genre_id: 1},
  {title: "Adiós Arrabal", composer: "Juan Baüer", lyricist: "Carlos Lenzi", year: 1930, genre_id: 1},
  {title: "Adiós Buenos Aires", composer: "Eduardo Arolas", lyricist: "Leopoldo Torres Ríos", year: nil, genre_id: 1},
  {title: "Adiós Pampa Mía", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1945, genre_id: 1},
  {title: "Afiches", composer: "Atilio Stampone", lyricist: "Homero Expósito", year: nil, genre_id: 1},
  {title: "Ahora No Me Conocés", composer: "Armando Baliotti", lyricist: "Carlos Giampetruzzi (Giampé)", year: 1941, genre_id: 1},
  {title: "Al Compás De Un Tango", composer: "Alberto Suárez Villanueva", lyricist: "Oscar Rubens", year: 1942, genre_id: 1},
  {title: "Al Compás Del Corazón (Late Un Corazón)", composer: "Domingo Federico", lyricist: "Homero Expósito", year: 1942, genre_id: 1},
  {title: "Al Verla Pasar", composer: "Joaquín Mora", lyricist: "José María Contursi", year: nil, genre_id: 1},
  {title: "Alas Rotas", composer: "Edgardo Donato", lyricist: "Maruja Pacheco Huergo", year: nil, genre_id: 1},
  {title: "Alma De Bohemio", composer: "Roberto Firpo", lyricist: "Juan Andrés Caruso", year: 1914, genre_id: 1},
  {title: "Alma Mía", composer: "Diego Centeno", lyricist: "Héctor Marcó", year: 1936, genre_id: 2},
  {title: "Amarras", composer: "Carlos Marchisio", lyricist: "Carmelo Santiago", year: 1944, genre_id: 1},
  {title: "Amigos Que Yo Quiero", composer: "Hugo Gutiérrez", lyricist: "Hugo Gutiérrez", year: nil, genre_id: 1},
  {title: "Amurado", composer: "Pedro Maffia", lyricist: "José De Grandis", year: 1927, genre_id: 1},
  {title: "Anclao En París", composer: "Guillermo Barbieri", lyricist: "Enrique Cadícamo", year: 1931, genre_id: 1},
  {title: "Anoche A Las Dos", composer: "Raúl De Los Hoyos", lyricist: "Roberto Lino Cayol", year: 1926, genre_id: 1},
  {title: "Así Se Baila El Tango", composer: "Elías Randal", lyricist: " Marvil (Elizardo Martínez Vilas)", year: 1942, genre_id: 1},
  {title: "Atenti Pebeta", composer: "Ciriaco Ortiz", lyricist: "Celedonio Flores", year: 1929, genre_id: 1},
  {title: "Bailarín Compadrito", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: 1929, genre_id: 1},
  {title: "Bailarín De Contraseña", composer: "Víctor Felice", lyricist: "Carlos Lucero", year: nil, genre_id: 1},
  {title: "Bailemos", composer: "Pascual Mamone", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Bajo El Cono Azul", composer: "Alfredo De Angelis", lyricist: "Carmelo Volpe", year: 1943, genre_id: 1},
  {title: "Bajo Un Cielo De Estrellas", composer: "Enrique Francini", lyricist: "José María Contursi", year: 1941, genre_id: 2},
  {title: "Balada Para Un Loco", composer: "Astor Piazzolla", lyricist: "Horacio Ferrer", year: 1969, genre_id: 1},
  {title: "Bandoneón Arrabalero", composer: " Bachicha", lyricist: "Pascual Contursi", year: 1928, genre_id: 1},
  {title: "Barajando Recuerdos", composer: "Luis Visca", lyricist: "Enrique Cadícamo", year: nil, genre_id: 1},
  {title: "Barrio De Tango", composer: "Aníbal Troilo", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Bigotito", composer: "Edgardo Donato", lyricist: "Celedonio Flores", year: nil, genre_id: 5},
  {title: "Cada Vez Que Me Recuerdes", composer: "Mariano Mores", lyricist: "José María Contursi", year: 1943, genre_id: 1},
  {title: "Cafetín De Buenos Aires", composer: "Mariano Mores", lyricist: "Enrique Santos Discepolo", year: 1948, genre_id: 1},
  {title: "Café De Los Angelitos", composer: "José Razzano", lyricist: "José Razzano", year: 1944, genre_id: 1},
  {title: "Calla Bandoneón", composer: "Carlos Lazzari", lyricist: "Oscar Rubens", year: nil, genre_id: 1},
  {title: "Cambalache", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1934, genre_id: 1},
  {title: "Caminito", composer: "Juan De Dios Filiberto", lyricist: "Gabino Coria Peñaloza", year: 1926, genre_id: 1},
  {title: "Campo Afuera", composer: "Rodolfo Biagi", lyricist: "Homero Manzi", year: 1939, genre_id: 3},
  {title: "Canción De Rango (Pa Que Se Callen)", composer: "Raúl Kaplún", lyricist: "José María Suñé", year: 1942, genre_id: 1},
  {title: "Canción Desesperada", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1945, genre_id: 1},
  {title: "Cantando", composer: "Mercedes Simone", lyricist: "Mercedes Simone", year: 1931, genre_id: 1},
  {title: "Caricias", composer: "María Isolina Godard", lyricist: "Juan Andrés Caruso", year: nil, genre_id: 1},
  {title: "Carillón De La Merced", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1931, genre_id: 1},
  {title: "Carnaval De Mi Barrio", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1938, genre_id: 1},
  {title: "Cascabelito", composer: "José Bohr", lyricist: "Juan Andrés Caruso", year: 1924, genre_id: 1},
  {title: "Chapaleando Barro", composer: "Arturo Castillo", lyricist: "Celedonio Flores", year: nil, genre_id: 1},
  {title: "Charlemos", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1940, genre_id: 1},
  {title: "Che Bandoneón", composer: "Aníbal Troilo", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Chorra", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1928, genre_id: 1},
  {title: "Como Dos Extraños", composer: "Pedro Laurenz", lyricist: "José María Contursi", year: 1940, genre_id: 1},
  {title: "Como El Hornero", composer: "Manuel Sucher", lyricist: "José Rótulo", year: 1944, genre_id: 1},
  {title: "Compadrón", composer: "Luis Visca", lyricist: "Enrique Cadícamo", year: 1927, genre_id: 1},
  {title: "Con Alma Y Vida", composer: "Carlos Di Sarli", lyricist: "Héctor Marcó", year: nil, genre_id: 3},
  {title: "Condena", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1937, genre_id: 1},
  {title: "Confesión", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1931, genre_id: 1},
  {title: "Convencernos", composer: "Eladia Blázquez", lyricist: "Eladia Blázquez", year: nil, genre_id: 1},
  {title: "Corazón", composer: "Carlos Di Sarli", lyricist: "Héctor Marcó", year: 1939, genre_id: 1},
  {title: "Corazón De Oro", composer: "Francisco Canaro", lyricist: "Jesús Fernández Blanco", year: nil, genre_id: 2},
  {title: "Corazón, No Le Hagas Caso!", composer: "Armando Pontier", lyricist: "Carlos Bahr", year: 1943, genre_id: 1},
  {title: "Corrientes Y Esmeralda", composer: "Francisco Pracánico", lyricist: "Celedonio Flores", year: 1933, genre_id: 1},
  {title: "Cosas Olvidadas", composer: "Antonio Rodio", lyricist: "José María Contursi", year: 1940, genre_id: 1},
  {title: "Cristal", composer: "Mariano Mores", lyricist: "José María Contursi", year: 1944, genre_id: 1},
  {title: "Cualquier Cosa", composer: "Herminia Velich", lyricist: "Herminia Velich", year: 1927, genre_id: 1},
  {title: "Cuando Llegue El Invierno", composer: "José Márquez", lyricist: "José Márquez", year: 1948, genre_id: 1},
  {title: "Cuando No Se Quiere Más", composer: "Roberto Rufino", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Cuando Un Viejo Se Enamora", composer: "Rodolfo Sciammarella", lyricist: "Manuel Romero", year: nil, genre_id: 3},
  {title: "Cuartito Azul", composer: "Mariano Mores", lyricist: "Mario Battistella", year: 1939, genre_id: 1},
  {title: "Cuatro Lágrimas", composer: "Lito Bayardo", lyricist: "Lito Bayardo", year: 1945, genre_id: 1},
  {title: "Cuatro Palabras", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: nil, genre_id: 2},
  {title: "Cuesta Abajo", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1934, genre_id: 1},
  {title: "Danza Maligna", composer: "Fernando Randle", lyricist: "Claudio Frollo", year: nil, genre_id: 1},
  {title: "De Mi Barrio", composer: "Roberto Goyheneche", lyricist: "Roberto Goyheneche", year: 1923, genre_id: 1},
  {title: "De Puro Curda", composer: "Carlos Olmedo", lyricist: "Abel Aznar", year: 1957, genre_id: 1},
  {title: "De Puro Guapo", composer: "Rafael Iriarte", lyricist: "Juan Carlos Fernández Díaz", year: 1927, genre_id: 1},
  {title: "Decile Que Vuelva", composer: "Miguel Bucino", lyricist: "Miguel Bucino", year: nil, genre_id: 1},
  {title: "Derrotado (Tenés Razón)", composer: "Antonio Arcieri", lyricist: "José Terragno", year: nil, genre_id: 1},
  {title: "Desde El Alma", composer: "Rosita Melo", lyricist: "Homero Manzi", year: 1947, genre_id: 2},
  {title: "Desencanto", composer: "Enrique Santos Discepolo", lyricist: "Luis César Amadori", year: 1936, genre_id: 1},
  {title: "Desencuentro", composer: "Aníbal Troilo", lyricist: "Cátulo Castillo", year: 1962, genre_id: 1},
  {title: "Después", composer: "Hugo Gutiérrez", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Destellos", composer: "Francisco Canaro", lyricist: "Juan Andrés Caruso", year: 1924, genre_id: 1},
  {title: "Dime Mi Amor", composer: "Rodolfo Sciammarella", lyricist: "Manuel Romero", year: nil, genre_id: 1},
  {title: "Din Don", composer: "Alberto Suárez Villanueva", lyricist: "Evaristo Fratantoni", year: nil, genre_id: 1},
  {title: "Duelo Criollo", composer: "Juan Rezzano", lyricist: "Lito Bayardo", year: 1928, genre_id: 1},
  {title: "Déjame No Quiero Verte Más", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: nil, genre_id: 1},
  {title: "Dónde Estás Corazón", composer: "Luis Martínez Serrano", lyricist: "Luis Martínez Serrano", year: 1930, genre_id: 1},
  {title: "El Abrojito", composer: "Luis Bernstein", lyricist: "Jesús Fernández Blanco", year: 1926, genre_id: 1},
  {title: "El Adiós", composer: "Maruja Pacheco Huergo", lyricist: "Virgilio San Clemente", year: 1937, genre_id: 1},
  {title: "El Choclo", composer: "Ángel Villoldo", lyricist: "Enrique Santos Discepolo", year: nil, genre_id: 1},
  {title: "El Ciruja", composer: "Ernesto De La Cruz", lyricist: "Alfredo Marino", year: 1926, genre_id: 1},
  {title: "El Día Que Me Quieras", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 6},
  {title: "El Firulete", composer: "Mariano Mores", lyricist: "Rodolfo Taboada", year: nil, genre_id: 3},
  {title: "El Fueye De Arolas", composer: "Héctor Marcó", lyricist: "Héctor Marcó", year: nil, genre_id: 1},
  {title: "El Huracán", composer: "Osvaldo Donato", lyricist: "Nolo López", year: nil, genre_id: 1},
  {title: "El Motivo", composer: "Juan Carlos Cobián", lyricist: "Pascual Contursi", year: nil, genre_id: 1},
  {title: "El Olivo", composer: "Antonio Scatasso", lyricist: "Carlos Cabral", year: 1924, genre_id: 1},
  {title: "El Pañuelito", composer: "Juan De Dios Filiberto", lyricist: "Gabino Coria Peñaloza", year: 1920, genre_id: 1},
  {title: "El Vals Soñador", composer: "Armando Pontier", lyricist: "Oscar Rubens", year: nil, genre_id: 2},
  {title: "El Yacaré", composer: "Alfredo Attadía", lyricist: "Mario Soto", year: nil, genre_id: 1},
  {title: "El último Café", composer: "Héctor Stamponi", lyricist: "Cátulo Castillo", year: nil, genre_id: 1},
  {title: "El último Organito", composer: "Acho Manzi", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Embrujamiento", composer: "Ricardo Malerba", lyricist: "Manuel Ferradás Campos", year: nil, genre_id: 1},
  {title: "En Carne Propia", composer: "Manuel Sucher", lyricist: "Carlos Bahr", year: 1944, genre_id: 1},
  {title: "En Esta Tarde Gris", composer: "Mariano Mores", lyricist: "José María Contursi", year: 1941, genre_id: 1},
  {title: "En La Buena Y En La Mala", composer: "Domingo Scarpino", lyricist: "Enrique Cadícamo", year: nil, genre_id: 1},
  {title: "En Tus Brazos", composer: "Carlos Zárate", lyricist: " Marvil (Elizardo Martínez Vilas)", year: nil, genre_id: 1},
  {title: "Entre Pitada Y Pitada", composer: "Rodolfo Sciammarella", lyricist: "Rodolfo Sciammarella", year: nil, genre_id: 3},
  {title: "Esquinas Porteñas", composer: "Sebastián Piana", lyricist: "Homero Manzi", year: 1933, genre_id: 2},
  {title: "Esta Noche Al Pasar", composer: "Héctor Grané", lyricist: "Justo Ricardo Thompson", year: 1945, genre_id: 1},
  {title: "Esta Noche De Luna", composer: "José García", lyricist: "Héctor Marcó", year: 1943, genre_id: 1},
  {title: "Esta Noche En Buenos Aires", composer: "Ángel Dagostino", lyricist: " Avlis (Erasmo Silva Cabrera)", year: 1944, genre_id: 1},
  {title: "Esta Noche Me Emborracho", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1928, genre_id: 1},
  {title: "Estampa Federal", composer: "Pedro Maffia", lyricist: "Cátulo Castillo", year: nil, genre_id: 2},
  {title: "Este Es Tu Tango", composer: "Enrique Mora", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Farol", composer: "Virgilio Expósito", lyricist: "Homero Expósito", year: 1943, genre_id: 1},
  {title: "Flor De Lino", composer: "Héctor Stamponi", lyricist: "Homero Expósito", year: 1947, genre_id: 6},
  {title: "Flores Del Alma", composer: "Juan Larenza", lyricist: "Alfredo Lucero Palacios", year: nil, genre_id: 2},
  {title: "Fuimos", composer: "José Dames", lyricist: "Homero Manzi", year: 1945, genre_id: 1},
  {title: "Fumando Espero", composer: "Juan Viladomat", lyricist: "Félix Garzo", year: 1922, genre_id: 1},
  {title: "Garganta Con Arena", composer: "Cacho Castaña", lyricist: "Cacho Castaña", year: 1993, genre_id: 1},
  {title: "Garúa", composer: "Aníbal Troilo", lyricist: "Enrique Cadícamo", year: 1943, genre_id: 1},
  {title: "Gitana Rusa", composer: "Juan Sánchez Gorio", lyricist: "Horacio Sanguinetti", year: 1942, genre_id: 1},
  {title: "Gricel", composer: "Mariano Mores", lyricist: "José María Contursi", year: 1942, genre_id: 1},
  {title: "Griseta", composer: "Enrique Delfino", lyricist: "José González Castillo", year: 1924, genre_id: 1},
  {title: "Gólgota", composer: "Rodolfo Biagi", lyricist: "Francisco Gorrindo", year: 1938, genre_id: 1},
  {title: "Hasta Siempre Amor", composer: "Donato Racciatti", lyricist: "Federico Silva", year: 1953, genre_id: 1},
  {title: "Hay Que Vivirla Compadre", composer: "Ángel Dagostino", lyricist: "Héctor Marcó", year: nil, genre_id: 1},
  {title: "Historia De Un Amor", composer: "Carlos Almarán", lyricist: "Carlos Almarán", year: nil, genre_id: 6},
  {title: "Humillación", composer: "Rodolfo Biagi", lyricist: "Carlos Bahr", year: 1941, genre_id: 1},
  {title: "Ilusión Azul", composer: "Arquímedes Arci", lyricist: "Arquímedes Arci", year: nil, genre_id: 2},
  {title: "Infamia", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1941, genre_id: 1},
  {title: "Inútil", composer: "Tito Ribero", lyricist: "Reinaldo Yiso", year: nil, genre_id: 1},
  {title: "Jacinto Chiclana", composer: "Astor Piazzolla", lyricist: "Jorge Luis Borges", year: nil, genre_id: 3},
  {title: "Jamás Retornarás", composer: "Osmar Maderna", lyricist: "Osmar Maderna", year: 1942, genre_id: 1},
  {title: "Junto A Tu Corazón", composer: "Enrique Francini", lyricist: "José María Contursi", year: 1942, genre_id: 1},
  {title: "La Abandoné Y No Sabía", composer: "José Canet", lyricist: "José Canet", year: 1943, genre_id: 1},
  {title: "La Bicicleta Blanca", composer: "Astor Piazzolla", lyricist: "Horacio Ferrer", year: nil, genre_id: 6},
  {title: "La Bruja", composer: "Juan Polito", lyricist: "Francisco Gorrindo", year: 1938, genre_id: 1},
  {title: "La Cachila", composer: "Eduardo Arolas", lyricist: "Héctor Polito", year: nil, genre_id: 1},
  {title: "La Canción De Buenos Aires", composer: "Orestes Cúfaro", lyricist: "Manuel Romero", year: 1933, genre_id: 1},
  {title: "La Capilla Blanca", composer: "Carlos Di Sarli", lyricist: "Héctor Marcó", year: 1944, genre_id: 1},
  {title: "La Casita De Mis Viejos", composer: "Juan Carlos Cobián", lyricist: "Enrique Cadícamo", year: 1932, genre_id: 1},
  {title: "La Copa Del Olvido", composer: "Enrique Delfino", lyricist: "Alberto Vacarezza", year: 1921, genre_id: 1},
  {title: "La Cumparsita", composer: "Gerardo Matos Rodríguez", lyricist: "Pascual Contursi / Enrique Maroni", year: nil, genre_id: 1},
  {title: "La Mariposa", composer: "Pedro Maffia", lyricist: "Celedonio Flores", year: 1923, genre_id: 1},
  {title: "La Melodía Del Corazón", composer: "Fioravante Di Cicco", lyricist: "Carmelo Santiago", year: nil, genre_id: 1},
  {title: "La Milonga De Buenos Aires", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1939, genre_id: 3},
  {title: "La Morocha", composer: "Enrique Saborido", lyricist: "Ángel Villoldo", year: 1905, genre_id: 1},
  {title: "La Mulateada", composer: "Julio Eduardo Del Puerto", lyricist: "Carlos Pesce", year: nil, genre_id: 3},
  {title: "La Piba De Los Jazmines", composer: "Ricardo Malerba", lyricist: "Julio Navarrine", year: nil, genre_id: 1},
  {title: "La Vida Es Corta", composer: "Ricardo Tanturi", lyricist: "Francisco Gorrindo", year: nil, genre_id: 1},
  {title: "La última Copa", composer: "Francisco Canaro", lyricist: "Juan Andrés Caruso", year: 1926, genre_id: 1},
  {title: "La última Curda", composer: "Aníbal Troilo", lyricist: "Cátulo Castillo", year: 1956, genre_id: 1},
  {title: "Lejos De Buenos Aires", composer: "Alberto Suárez Villanueva", lyricist: "Oscar Rubens", year: 1942, genre_id: 1},
  {title: "Lilián", composer: "Héctor Varela", lyricist: "Luis Caruso", year: 1944, genre_id: 1},
  {title: "Lloran Las Campanas", composer: "Alberto Suárez Villanueva", lyricist: "Oscar Rubens", year: 1944, genre_id: 1},
  {title: "Llorar Por Una Mujer", composer: "Enrique Rodríguez", lyricist: "Enrique Cadícamo", year: nil, genre_id: 1},
  {title: "Lo Han Visto Con Otra", composer: "Horacio Pettorossi", lyricist: "Horacio Pettorossi", year: 1928, genre_id: 1},
  {title: "Lo Que Vos Te Merecés", composer: "Carlos Olmedo", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Los Mareados", composer: "Juan Carlos Cobián", lyricist: "Enrique Cadícamo", year: 1942, genre_id: 1},
  {title: "Lunes", composer: "José Luis Padula", lyricist: "Francisco García Jiménez", year: 1927, genre_id: 1},
  {title: "Madame Ivonne", composer: "Eduardo Pereyra", lyricist: "Enrique Cadícamo", year: 1933, genre_id: 1},
  {title: "Madreselva", composer: "Francisco Canaro", lyricist: "Luis César Amadori", year: 1931, genre_id: 1},
  {title: "Malena", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1941, genre_id: 1},
  {title: "Malevaje", composer: "Juan De Dios Filiberto", lyricist: "Enrique Santos Discepolo", year: 1929, genre_id: 1},
  {title: "Mandria", composer: "Juan Rodríguez", lyricist: "Francisco Brancatti", year: nil, genre_id: 1},
  {title: "Mano A Mano", composer: "Carlos Gardel", lyricist: "Celedonio Flores", year: 1923, genre_id: 1},
  {title: "Maquillaje", composer: "Virgilio Expósito", lyricist: "Homero Expósito", year: nil, genre_id: 1},
  {title: "Marioneta", composer: "Juan José Guichandut", lyricist: "Armando Tagini", year: 1928, genre_id: 1},
  {title: "Mariposita", composer: "Anselmo Aieta", lyricist: "Francisco García Jiménez", year: 1941, genre_id: 1},
  {title: "Marol", composer: "Alberto Nery", lyricist: "Federico Silva", year: nil, genre_id: 1},
  {title: "Maula", composer: "Adolfo Mondino", lyricist: "Víctor Soliño", year: 1927, genre_id: 1},
  {title: "Mañana Zarpa Un Barco", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Me Quedé Mirándola", composer: "Vicente Spina", lyricist: "Roberto Miró", year: 1945, genre_id: 1},
  {title: "Mendocina", composer: "Miguel Bruno", lyricist: "Benigno Palmeiro", year: nil, genre_id: 2},
  {title: "Metido (Enamorado)", composer: " Príncipe Cubano", lyricist: " Príncipe Cubano", year: nil, genre_id: 1},
  {title: "Mi Buenos Aires Querido", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1934, genre_id: 1},
  {title: "Mi Dolor", composer: "Carlos Marcucci", lyricist: "Manuel Meaños", year: 1930, genre_id: 1},
  {title: "Mi Noche Triste (Lita)", composer: "Samuel Castriota", lyricist: "Pascual Contursi", year: 1916, genre_id: 1},
  {title: "Mi Serenata", composer: "Edgardo Donato", lyricist: "Juan Carlos Thorry", year: nil, genre_id: 1},
  {title: "Mi Taza De Café", composer: "Alfredo Malerba", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Milonga Que Peina Canas", composer: "Alberto Gómez", lyricist: "Alberto Gómez", year: 1942, genre_id: 3},
  {title: "Milonga Querida", composer: "Juan Larenza", lyricist: "Lito Bayardo", year: nil, genre_id: 3},
  {title: "Milonga Triste", composer: "Sebastián Piana", lyricist: "Homero Manzi", year: 1936, genre_id: 3},
  {title: "Milonguita (Esthercita)", composer: "Enrique Delfino", lyricist: "Samuel Linnig", year: 1920, genre_id: 1},
  {title: "Mis Harapos", composer: "Marino García", lyricist: "Jorge Luque Lobos", year: nil, genre_id: 6},
  {title: "Moneda De Cobre", composer: "Carlos Viván", lyricist: "Horacio Sanguinetti", year: 1942, genre_id: 1},
  {title: "Muchacho", composer: "Edgardo Donato", lyricist: "Celedonio Flores", year: 1926, genre_id: 1},
  {title: "Muchachos Comienza La Ronda", composer: "Luis Porcell", lyricist: "Leopoldo Díaz Vélez", year: 1943, genre_id: 1},
  {title: "Murió El Malevo", composer: "Héctor Varela", lyricist: "Carlos Waiss", year: nil, genre_id: 1},
  {title: "Muñeca Brava", composer: "Luis Visca", lyricist: "Enrique Cadícamo", year: 1929, genre_id: 1},
  {title: "Nada Más", composer: "Juan Darienzo", lyricist: "Juan Darienzo", year: 1938, genre_id: 1},
  {title: "Naranjo En Flor", composer: "Virgilio Expósito", lyricist: "Homero Expósito", year: 1944, genre_id: 1},
  {title: "Nido Gaucho", composer: "Carlos Di Sarli", lyricist: "Héctor Marcó", year: 1942, genre_id: 1},
  {title: "Niebla Del Riachuelo", composer: "Juan Carlos Cobián", lyricist: "Enrique Cadícamo", year: 1937, genre_id: 1},
  {title: "Ninguna", composer: "Raúl Fernández Siro", lyricist: "Homero Manzi", year: 1942, genre_id: 1},
  {title: "Niño Bien", composer: "Juan Antonio Collazo", lyricist: "Víctor Soliño", year: 1928, genre_id: 1},
  {title: "No Hay Tierra Como La Mía", composer: " Charlo", lyricist: "Enrique Cadícamo", year: nil, genre_id: 3},
  {title: "No Me Escribas", composer: "Agustín Bardi", lyricist: "Juan Andrés Caruso", year: 1927, genre_id: 1},
  {title: "No Me Pregunten Por Qué", composer: "Carlos Di Sarli", lyricist: "Reynaldo Pignataro", year: 1935, genre_id: 1},
  {title: "No Mientas", composer: "Héctor Varela", lyricist: "Héctor Marcó", year: nil, genre_id: 1},
  {title: "No Te Apures, Carablanca", composer: "Roberto Garza", lyricist: "Carlos Bahr", year: 1942, genre_id: 1},
  {title: "Noche De Reyes", composer: "Pedro Maffia", lyricist: "Jorge Curi", year: 1926, genre_id: 1},
  {title: "Nostalgias", composer: "Juan Carlos Cobián", lyricist: "Enrique Cadícamo", year: 1936, genre_id: 1},
  {title: "Nunca Tuvo Novio", composer: "Agustín Bardi", lyricist: "Enrique Cadícamo", year: 1930, genre_id: 1},
  {title: "Oigo Tu Voz", composer: "Mario Canaro", lyricist: "Francisco García Jiménez", year: nil, genre_id: 1},
  {title: "Olvidao", composer: "Guillermo Barbieri", lyricist: "Enrique Cadícamo", year: 1932, genre_id: 1},
  {title: "Oro Y Plata", composer: " Charlo", lyricist: "Homero Manzi", year: 1943, genre_id: 3},
  {title: "Pa Qué Seguir", composer: "Francisco Fiorentino", lyricist: "Pedro Lloret", year: nil, genre_id: 1},
  {title: "Paciencia", composer: "Juan Darienzo", lyricist: "Francisco Gorrindo", year: 1937, genre_id: 1},
  {title: "Paisaje", composer: "Sebastián Piana", lyricist: "Homero Manzi", year: 1943, genre_id: 2},
  {title: "Pasional", composer: "Jorge Caldara", lyricist: "Mario Soto", year: 1951, genre_id: 1},
  {title: "Patotero Sentimental", composer: "Manuel Jovés", lyricist: "Manuel Romero", year: 1922, genre_id: 1},
  {title: "Pensalo Bien", composer: "Alberto Calvera", lyricist: "Enrique López", year: nil, genre_id: 1},
  {title: "Percal", composer: "Domingo Federico", lyricist: "Homero Expósito", year: 1943, genre_id: 1},
  {title: "Pero Yo Sé", composer: "Azucena Maizani", lyricist: "Azucena Maizani", year: 1928, genre_id: 1},
  {title: "Pobre Flor (Primera Ilusión)", composer: "Luis Mottolese", lyricist: "Víctor Spindola", year: nil, genre_id: 2},
  {title: "Pocas Palabras", composer: "Ricardo Tanturi", lyricist: "Enrique Cadícamo", year: 1941, genre_id: 1},
  {title: "Poema", composer: "Eduardo Bianco / Mario Melfi", lyricist: "Mario Melfi / Eduardo Bianco", year: nil, genre_id: 1},
  {title: "Por Qué Canto Así", composer: "José Razzano", lyricist: "Celedonio Flores", year: 1943, genre_id: 1},
  {title: "Por Qué La Quise Tanto", composer: "Mariano Mores", lyricist: "Rodolfo Taboada", year: nil, genre_id: 1},
  {title: "Por Una Cabeza", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Prohibido", composer: "Manuel Sucher", lyricist: "Carlos Bahr", year: nil, genre_id: 1},
  {title: "Pájaro Ciego", composer: "Antonio Bonavena", lyricist: "Lito Bayardo", year: nil, genre_id: 1},
  {title: "Que Falta Que Me Hacés", composer: "Armando Pontier", lyricist: "Federico Silva", year: nil, genre_id: 1},
  {title: "Que No Sepan Las Estrellas", composer: "José Ranieri", lyricist: "Alfredo Faustino Roldán", year: 1945, genre_id: 1},
  {title: "Que Nunca Me Falte", composer: "Héctor Morales", lyricist: "Héctor Marcó", year: 1937, genre_id: 1},
  {title: "Que Se Vayan", composer: "Francisco Canosa", lyricist: "Enrique Dizeo", year: 1929, genre_id: 1},
  {title: "Quiero Verte Una Vez Más", composer: "Mario Canaro", lyricist: "José María Contursi", year: 1939, genre_id: 1},
  {title: "Qué Bien Te Queda (Cómo Has Cambiado)", composer: "Vicente Salerno", lyricist: "Juan Mazaroni", year: 1944, genre_id: 1},
  {title: "Qué Será De Ti", composer: "Roberto Nievas Blanco", lyricist: "Julio Jorge Nelson", year: nil, genre_id: 1},
  {title: "Qué Tango Hay Que Cantar", composer: "Rubén Juárez", lyricist: "Cacho Castaña", year: nil, genre_id: 1},
  {title: "Qué Te Importa Que Te Llore", composer: "Miguel Caló", lyricist: "Miguel Caló", year: 1942, genre_id: 1},
  {title: "Recién", composer: "Osvaldo Pugliese", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Recuerdo Malevo", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1933, genre_id: 1},
  {title: "Recuerdos De La Pampa", composer: "Rodolfo Duclós", lyricist: "Rodolfo Duclós", year: nil, genre_id: 1},
  {title: "Remembranza", composer: "Mario Melfi", lyricist: "Mario Battistella", year: 1934, genre_id: 1},
  {title: "Romance De Barrio", composer: "Aníbal Troilo", lyricist: "Homero Manzi", year: 1947, genre_id: 2},
  {title: "Rondando Tu Esquina", composer: " Charlo", lyricist: "Enrique Cadícamo", year: 1945, genre_id: 1},
  {title: "Ríe Payaso", composer: "Virgilio Carmona", lyricist: "Emilio Falero", year: 1929, genre_id: 1},
  {title: "Se Dice De Mí", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1943, genre_id: 3},
  {title: "Se Lustra Señor", composer: "Enrique Alessio", lyricist: " Marvil (Elizardo Martínez Vilas)", year: 1946, genre_id: 1},
  {title: "Señores Yo Soy Del Centro", composer: "Armando Baliotti", lyricist: "Santiago Adamini", year: nil, genre_id: 3},
  {title: "Siempre Es Carnaval", composer: "Osvaldo Fresedo", lyricist: "Emilio Fresedo", year: 1937, genre_id: 1},
  {title: "Silbando", composer: "Sebastián Piana / Cátulo Castillo", lyricist: "José González Castillo", year: 1925, genre_id: 1},
  {title: "Silencio", composer: "Carlos Gardel / Horacio Pettorossi", lyricist: "Alfredo Le Pera / Horacio Pettorossi", year: 1932, genre_id: 1},
  {title: "Sin Palabras", composer: "Mariano Mores", lyricist: "Enrique Santos Discepolo", year: 1946, genre_id: 1},
  {title: "Sin Rumbo Fijo", composer: "Eugenio Carrere", lyricist: "Eugenio Carrere", year: nil, genre_id: 1},
  {title: "Solamente Ella", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Sosiego En La Noche", composer: "Roberto Garza", lyricist: "Carlos Bahr", year: 1943, genre_id: 1},
  {title: "Soy Aquel Viajero", composer: "Héctor Grané", lyricist: "Justo Ricardo Thompson", year: nil, genre_id: 1},
  {title: "Soñar Y Nada Más", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: 1943, genre_id: 2},
  {title: "Sus Ojos Se Cerraron", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Tabernero (El Tabernero)", composer: "Fausto Frontera", lyricist: "Raúl Costa Oliveri", year: 1927, genre_id: 1},
  {title: "Tal Vez Será Su Voz", composer: "Lucio Demare", lyricist: "Homero Manzi", year: 1943, genre_id: 1},
  {title: "Te Aconsejo Que Me Olvides", composer: "Pedro Maffia", lyricist: "Jorge Curi", year: 1926, genre_id: 1},
  {title: "Tinta Roja", composer: "Sebastián Piana", lyricist: "Cátulo Castillo", year: 1941, genre_id: 1},
  {title: "Toda Mi Vida", composer: "Aníbal Troilo", lyricist: "José María Contursi", year: 1941, genre_id: 1},
  {title: "Todo Te Nombra", composer: "Francisco Canaro", lyricist: "Ivo Pelay", year: nil, genre_id: 1},
  {title: "Tomo Y Obligo", composer: "Carlos Gardel", lyricist: "Manuel Romero", year: 1931, genre_id: 1},
  {title: "Tormenta", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1939, genre_id: 1},
  {title: "Torrente", composer: "Hugo Gutiérrez", lyricist: "Homero Manzi", year: 1944, genre_id: 1},
  {title: "Trasnochando", composer: "Armando Baliotti", lyricist: "Santiago Adamini", year: 1942, genre_id: 1},
  {title: "Tres Amigos", composer: "Enrique Cadícamo", lyricist: "Enrique Cadícamo", year: 1944, genre_id: 1},
  {title: "Tres Esquinas", composer: "Ángel Dagostino", lyricist: "Enrique Cadícamo", year: 1941, genre_id: 1},
  {title: "Triste Comedia", composer: "Héctor Stamponi", lyricist: "Oscar Rubens", year: 1949, genre_id: 1},
  {title: "Tristeza Marina", composer: "José Dames", lyricist: "Horacio Sanguinetti", year: 1943, genre_id: 1},
  {title: "Tu Angustia Y Mi Dolor", composer: "Alfredo Gobbi", lyricist: "Julio Camilloni", year: nil, genre_id: 1},
  {title: "Tu Boca Mintió", composer: "Armando Angeletti", lyricist: "Alberto Longo", year: nil, genre_id: 1},
  {title: "Tu Diagnóstico", composer: "José Betinotti", lyricist: "José Betinotti", year: nil, genre_id: 2},
  {title: "Tu Vieja Ventana", composer: "Guillermo Barbieri", lyricist: "Ambrosio Río", year: nil, genre_id: 2},
  {title: "Tus Labios Me Dirán", composer: "Emilio Brameri", lyricist: "Héctor Negro", year: nil, genre_id: 1},
  {title: "Tú El Cielo Y Tú", composer: "Mario Canaro", lyricist: "Héctor Marcó", year: 1944, genre_id: 1},
  {title: "Un Crimen", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: nil, genre_id: 1},
  {title: "Una Emoción", composer: "Raúl Kaplún", lyricist: "José María Suñé", year: 1943, genre_id: 1},
  {title: "Una Lágrima Tuya", composer: "Mariano Mores", lyricist: "Homero Manzi", year: 1949, genre_id: 1},
  {title: "Una Noche De Garufa", composer: "Eduardo Arolas", lyricist: "Gabriel Clausi", year: nil, genre_id: 1},
  {title: "Una Pena", composer: "Adolfo Rosquellas", lyricist: "Arturo Albert", year: 1923, genre_id: 1},
  {title: "Una Piba Como Vos", composer: "Dante Gilardoni", lyricist: "Dante Gilardoni", year: nil, genre_id: 1},
  {title: "Vamos", composer: "Feliciano Brunelli", lyricist: "Rodolfo Sciammarella", year: 1944, genre_id: 1},
  {title: "Ventanita De Arrabal", composer: "Antonio Scatasso", lyricist: "Pascual Contursi", year: 1927, genre_id: 1},
  {title: "Ventarrón", composer: "Pedro Maffia", lyricist: "José Horacio Staffolani", year: 1933, genre_id: 1},
  {title: "Verdemar", composer: "Carlos Di Sarli", lyricist: "José María Contursi", year: 1943, genre_id: 1},
  {title: "Vida Mía", composer: "Osvaldo Fresedo", lyricist: "Emilio Fresedo", year: 1933, genre_id: 1},
  {title: "Vieja Recova", composer: "Rodolfo Sciammarella", lyricist: "Enrique Cadícamo", year: 1930, genre_id: 1},
  {title: "Viejo Portón", composer: "Héctor Palacios", lyricist: "Máximo Orsi", year: nil, genre_id: 2},
  {title: "Violín", composer: "Ricardo Malerba / Dante Smurra", lyricist: "Horacio Sanguinetti", year: nil, genre_id: 1},
  {title: "Volver", composer: "Carlos Gardel", lyricist: "Alfredo Le Pera", year: 1935, genre_id: 1},
  {title: "Volver A Vernos", composer: "Joaquín Mora", lyricist: "Luis Castiñeira", year: nil, genre_id: 1},
  {title: "Volvé Mi Negra", composer: "José María Rizzuti", lyricist: "José Diez Gómez", year: nil, genre_id: 1},
  {title: "Vuelves", composer: "María Esther Pacheco Huergo", lyricist: "Virgilio San Clemente", year: 1939, genre_id: 1},
  {title: "Vuelvo Al Sur", composer: "Astor Piazzolla", lyricist: "Fernando \"Pino\" Solanas", year: nil, genre_id: 1},
  {title: "Whisky", composer: "Héctor Marcó", lyricist: "Héctor Marcó", year: 1957, genre_id: 1},
  {title: "Y Todavía Te Quiero", composer: "Luciano Leocata", lyricist: "Abel Aznar", year: nil, genre_id: 1},
  {title: "Ya Sale El Tren", composer: "Luis Rubistein", lyricist: "Luis Rubistein", year: 1943, genre_id: 1},
  {title: "Yira Yira", composer: "Enrique Santos Discepolo", lyricist: "Enrique Santos Discepolo", year: 1930, genre_id: 1},
  {title: "Yo Me Llamo Juan Te Quiero", composer: "Antonio Molina", lyricist: "Fernán Silva Valdés", year: nil, genre_id: 3},
  {title: "Yo No Sé Que Me Han Hecho Tus Ojos", composer: "Francisco Canaro", lyricist: "Francisco Canaro", year: nil, genre_id: 2},
  {title: "Yo Soy De San Telmo", composer: "Arturo Gallucci", lyricist: "Victorino Velázquez", year: nil, genre_id: 3},
  {title: "Yo También Soñé", composer: "Francisco Canaro", lyricist: "Luis César Amadori", year: 1935, genre_id: 1},
  {title: "Yo Te Adoro Bandoneón", composer: "Ramón Coll", lyricist: "Carlos Pesce", year: nil, genre_id: 1},
  {title: "Yuyo Verde", composer: "Domingo Federico", lyricist: "Homero Expósito", year: 1944, genre_id: 1},
  {title: "Zapatitos De Raso", composer: "Jorge Dragone", lyricist: "Fernando Caprio", year: nil, genre_id: 3},
  {title: "Zorzal", composer: "Dorita Zárate", lyricist: "Dorita Zárate", year: nil, genre_id: 3}
])
